# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDf0PCZY755B4Ev_ER6m1VRqsuZ7zEXV
"""

# Step 1: Import Libraries and Load Dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset (update the path if needed)
df = pd.read_csv('Titanic-Dataset.csv')

# Step 2: Explore Basic Info
print(df.info())
print(df.isnull().sum())

# Step 3: Handle Missing Values
# For numeric: Fill 'Age' with median, 'Fare' with mean
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Step 4: Convert Categorical Features (Encoding)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Label Encoding for 'Sex'
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

# One-hot encoding for 'Embarked'
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Step 5: Normalize/Standardize Numerical Features
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()
cols_to_scale = ['Age', 'Fare']

df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

# (Alternatively, use MinMaxScaler for normalization)
# scaler = MinMaxScaler()
# df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

# Step 6: Visualize Outliers with Boxplots
plt.figure(figsize=(10,5))
sns.boxplot(data=df[cols_to_scale])
plt.title('Boxplot of Numerical Features')
plt.show()

# Remove outliers using IQR method
for col in cols_to_scale:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

# Step 7: Save Cleaned Data
df.to_csv('titanic_cleaned.csv', index=False)

print("Data cleaned and saved to 'titanic_cleaned.csv'.")

